from datetime import date


class MockDataService:
    def gerar_dados_teste(self) -> dict[str, object]:
        hoje = date.today().isoformat()
        return {
            "nome": "Paciente Teste",
            "data_nascimento": "2017-05-15",
            "idade": "8",
            "escolar": "Escola Municipal Exemplo",
            "ano_escolar": "3º ano",
            "responsavel_presente": "Mãe",
            "cep": "01001-000",
            "endereco_logradouro": "Praça da Sé",
            "endereco_numero": "100",
            "endereco_complemento": "Apto 12",
            "endereco_bairro": "Sé",
            "endereco_cidade": "São Paulo",
            "endereco_estado": "SP",
            "data_avaliacao": hoje,
            "avaliadora": "Rosangema Monteiro de Camargo",
            "motivo_familia": "Dificuldade de leitura e atenção nas tarefas escolares.",
            "queixa_escolar": "Baixa fluência e lentidão na execução das atividades.",
            "historico_dificuldades": "Queixas iniciadas no 2º ano e aumentaram no último semestre.",
            "intercorrencias_gravidez": "Sem intercorrências relevantes.",
            "tipo_parto": "Cesárea",
            "prematuridade": False,
            "prematuridade_semanas": "",
            "tempo_uti": False,
            "tempo_uti_detalhes": "",
            "engatinhou": "9",
            "sentou": "7",
            "andou": "13",
            "primeiras_palavras": "12",
            "frases": "24",
            "controle_esfincter": "3 anos",
            "observacoes_marcos": "Desenvolvimento global sem atrasos significativos.",
            "atitude_inicial": "Tímido, mas colaborativo",
            "contato_visual": "Adequado",
            "resposta_instrucoes": "Compreende instruções simples",
            "foco_atencao_observacao": "Oscila ao longo da atividade",
            "persistencia_tarefa": "Necessita de reforço verbal",
            "controle_emocional": "Leve frustração diante de erros",
            "interacao_avaliadora": "Boa interação",
            "atividade_motora": "Sem alterações relevantes",
            "observacoes_gerais": "Aceitou bem as propostas lúdicas.",
            "instrumento_entrevista_responsaveis": True,
            "instrumento_observacao_ludica": True,
            "instrumento_desenhos": True,
            "instrumento_piaget": True,
            "instrumento_conservacao": True,
            "instrumento_classificacao": True,
            "instrumento_seriacao": True,
            "instrumento_linguagem": True,
            "instrumento_consciencia_fonologica": True,
            "instrumento_leitura_escrita": True,
            "instrumento_matematica": True,
            "instrumento_testes_projetivos": False,
            "instrumento_protocolos_especificos": False,
            "instrumento_outros": "Registro de observação em sessão.",
            "atencao_sustentacao": "Regular",
            "atencao_seletividade": "Adequada em ambiente estruturado",
            "atencao_alternancia": "Com dificuldade",
            "atencao_dispersa": "Sim, em tarefas longas",
            "atencao_comentarios": "Melhor desempenho com pausas curtas.",
            "memoria_auditiva_imediata": "Adequada",
            "memoria_visual_imediata": "Boa",
            "memoria_operacional": "Regular",
            "linguagem_compreensao_oral": "Boa",
            "linguagem_expressao_verbal": "Boa",
            "linguagem_vocabulario": "Compatível para idade",
            "linguagem_articulacao": "Adequada",
            "linguagem_fluencia": "Leves pausas",
            "raciocinio_sequencia_logica": "Regular",
            "raciocinio_categorizacao": "Boa",
            "raciocinio_comparacao": "Boa",
            "raciocinio_causa_efeito": "Adequada",
            "hipoteses_escrita": "silábico-alfabética",
            "leitura_fluencia": "Abaixo do esperado",
            "leitura_compreensao": "Regular",
            "leitura_velocidade": "Lenta",
            "escrita_letra": "Legível",
            "escrita_ortografia": "Erros frequentes em sílabas complexas",
            "escrita_construcao_frases": "Frases simples",
            "escrita_coerencia_textual": "Regular",
            "matematica_reconhecimento_numeros": "Adequado",
            "matematica_contagem": "Adequada",
            "matematica_operacoes_basicas": "Com apoio visual",
            "matematica_resolucao_problemas": "Com dificuldade",
            "matematica_raciocinio_logico": "Regular",
            "relacionamento_avaliadora": "Positivo",
            "relacionamento_pares": "Adequado",
            "autoestima": "Sensível a erros",
            "autonomia": "Parcial",
            "sinais_ansiedade_tristeza_dependencia": "Leve ansiedade em atividade formal.",
            "brincadeira_tipo_preferida": "Jogos de encaixe e construção",
            "brincadeira_imaginacao_simbolismo": "Presente",
            "brincadeira_interacao_social": "Boa",
            "brincadeira_organizacao_espaco": "Adequada",
            "brincadeira_persistencia_jogo": "Boa com incentivo",
            "hipotese_dificuldade_aprendizagem": "Indícios de dificuldade específica em leitura e escrita.",
            "indicios_tea": "Sem indícios significativos no contexto avaliado.",
            "indicios_tdah": "Sinais leves de desatenção; sugerida investigação complementar.",
            "dificuldades_pedagogicas_especificas": "Consciência fonológica e automatização da leitura.",
            "aspectos_emocionais_envolvidos": "Ansiedade de desempenho.",
            "fatores_ambientais_familiares": "Rotina de estudos pouco estruturada.",
            "recomendacao_familia": "Estabelecer rotina diária curta de leitura compartilhada.",
            "recomendacao_escola": "Adaptar tempo de tarefas escritas e oferecer reforço fonológico.",
            "encaminhamento_fonoaudiologia": True,
            "encaminhamento_terapia_ocupacional": False,
            "encaminhamento_psicoterapia": False,
            "encaminhamento_neuropediatra": False,
            "encaminhamento_psiquiatria": False,
            "encaminhamento_outros": "Acompanhamento psicopedagógico semanal.",
            "frequencia_recomendada": "1x por semana",
            "focos_intervencao": "Consciência fonológica, leitura funcional e autorregulação.",
            "metas_iniciais": "Aumentar fluência de leitura e reduzir erros ortográficos em 3 meses.",
            "parecer_final": "O perfil observado sugere dificuldade de aprendizagem com impacto em leitura e escrita, associada a oscilação atencional. Recomenda-se intervenção psicopedagógica contínua e monitoramento escolar/familiar.",
        }
